POST /todos HTTP/1.1
Host: localhost:9999
X-Request-ID: 1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA3MDIxNDJ9.NLdV65Y-a7yVCSiQScHQaSbAmpd9klZ1Nu3BBUmKJmU
Content-Type: application/json
Content-Length: 30

{
    "task":"Time In"
  
}